### PR TITLE
Allow comparative chart download

### PR DESCRIPTION
**Pull request by TaiWilkin**
## Overview

Updates the comparative chart download to correctly format the comparative "out of ten" chart titles. 

Connects #118 

### Demo

2020_2021_A 2_Out of 10 of your neighbors, how many do you think believe that girls and boys should share household tasks equally_ Please enter a whole number between 0 and 10 (1)

## Testing Instructions

 * Select a combination of geographies for multiple years and geographies for one year, then select multiple years and a question of each type (stacked bar chart, grouped bar chart, and waffle / out-of-ten chart). 
 * Download the image for each chart.
 * Download the CSV for each chart.
 * Download the CSV for the full page.
 * Repeat the above steps with only one year selected. 
 * The images and CSVs should download correctly and without errors.

### CODE REVIEW

**Comment by rajadain** [comment]
Taking a look now

**Comment by rajadain** [comment]
When generating a CSV for a stacked bar chart, the results have 2021 rows even though there are no values in the visual chart. Also, the numeric output is under Gender rather than Value:

image

**Comment by rajadain** [comment]
Actually, the above may be a problem in the configuration of some questions than a result of this PR. I see misquoted fields in the CSV here:

image

**Review by rajadain — APPROVED** [review]
+1 tested, this works well. Should make a follow up issue for the bug reported above.

**Comment by TaiWilkin** [comment]
Thank you for reviewing! I have added a followup issue for the text issue [here](https://github.com/azavea/fb-gender-survey-dashboard/issues/145).

**Pull request merged**
