### PR TITLE
Update About & FAQ text and final polish for mobile

### PR DESCRIPTION
**Pull request by alexelash**
## Overview
Styles the app to work on smaller screens and updates text according to FB's feedback.

Connects #80 

### Demo

Red banner
Screen Shot 2021-02-01 at 1 04 50 PM

Maxed width
Screen Shot 2021-02-01 at 3 13 35 PM

Mobile
Screen Shot 2021-02-01 at 3 13 59 PM

Screen Shot 2021-02-01 at 3 13 49 PM

Screen Shot 2021-02-01 at 3 14 10 PM

Screen Shot 2021-02-01 at 3 14 25 PM
Screen Shot 2021-02-01 at 3 14 35 PM
Screen Shot 2021-02-01 at 3 14 42 PM

### Notes
- I didn't go so far as to make the charts fully responsive due to time constraints - mobile users will be able to download nice-looking bar, stacked, and waffle charts, but they'll need to scroll left-right to see the full bar/stacked charts. Waffle charts are stacked.
- Breadcrumbs are hidden on very small screens as they would take up a lot of vertical reestate.
- @TaiWilkin I was able to do half of **043** and changed the color of the notification, but couldn't find where the time was set.
- Set a max-width for elements that were identified in **042**.
- Updated text according to **044, 049, 051, 052, 053, 054, & 055**.

## Testing Instructions
- `git pull`
- View all pages of app and ensure that it looks ok on smaller screens.
- Updated text according to **044, 049, 051, 052, 053, 054, & 055**. Please check my work 😬  I think I got everything!

### CODE REVIEW

**Comment by TaiWilkin** [comment]
Taking a look now. Thanks for your quick turnaround on that client feedback!

**Review by TaiWilkin — CHANGES_REQUESTED** [review]
- 42: The homepage is lined up now, and much improved. They didn't specifically mention the alignment concern for other pages of the app, but it does look like the main page content (such as the accordions) on other pages isn't set to the same width as the header content. 
- 43: The color looks great! I think they're just asking for a text change in terms of the 30-second/1-minute comment, since it says '30-second survey' in the notification.
- 44: 👍
- 49: I'm seeing a reference to 'codebook' under FAQ -> Is Data Provided for Regions and Countries the Same? It looks like you got all of the other spots I can find it!
- 51: 👍
- 52: 👍
- 53: 👍
- 54: 👍
- 55: 👍

Mobile: Mobile looks so much better than before! I agree that making the bar charts responsive for mobile could be pretty labor-intensive - I suspect it will involve specially rendering a separate version of the charts on mobile only. I think the waffle charts look very good and for the moment the scrolling is working well. 

Thanks again for grabbing all those text changes/etc!

**Comment by alexelash** [comment]
@TaiWilkin Great, thanks for the review! This should be ready for another look. I did a couple other little things while I was in there to make the app a bit faster / more accessible.

**Review by TaiWilkin — APPROVED** [review]
This looks wonderful! Thanks for all your hard work!

**Pull request merged**
