### PR TITLE
Add functional app template

### PR DESCRIPTION
**Pull request by mmcfarland**
## Overview
Brings in an app template modified to reflect anticipated dependencies
for this project. The environment successfully bootstraps with `setup`
and `server`, though additional changes may be required to adjust
other STRTA scripts.

Notable changes from the core template are:
- Vagrant base box upgraded to Ubuntu 20.04
- Uses Python3 for Ansible and VM-based script execution
 
Connects #1 

## Testing Instructions
After cloning the repository and checking out this branch:
- Run `./scripts/setup` to bootstrap the environment
- Log onto the VM and run the server to see the default CRA app hosted via WDS on http://localhost:3333
  `vagrant ssh && ./scripts/server`
- Check that other scripts (notably, not `cibuild`) are in working order
- Check that the documentation is generally correct

### CODE REVIEW

**Comment by TaiWilkin** [comment]
@mmcfarland `./scripts/setup` is failing with the message:
```
ERROR! the role 'azavea.pip' was not found in ansible.legacy:/vagrant/deployment/ansible/roles:/vagrant/deployment/ansible/roles:/vagrant/deployment/ansible/roles:/vagrant/deployment/ansible

The error appears to be in '/vagrant/deployment/ansible/roles/fb-gender-survey.docker/meta/main.yml': line 3, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

dependencies:
  - { role: azavea.pip }
    ^ here
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by mmcfarland** [comment]
Sorry, I left some debugging comments in. Reverted in a22b976.

**Review by TaiWilkin — APPROVED** [review]
This is working well! I was able to run all the scripts (except cibuild, of course) without issue, and the default CRA app loaded as expected.

**Comment by mmcfarland** [comment]
Thanks for the review. I should have destroyed and re-run the setup script one final time prior to opening this PR.

**Pull request merged**
